const selecionadoDados = [
    { id: 1, nome: 'Amarildo', src: '/assets/Amarildo.jpeg', descricao: 'Amarildo Tavares Silveira, mais conhecido como Amarildo é um treinador e ex-futebolista brasileiro que atuava como atacante.' },
    { id: 2, nome: 'Carlos Alberto Torres', src: '/assets/Carlos alberto torres.jpeg', descricao: 'Carlos Alberto Torres foi um futebolista, treinador e comentarista esportivo brasileiro. Em sua longa carreira, atuou como lateral-direito, tendo sido um dos símbolos do clássico futebol brasileiro, eternizado pela conquista do tricampeonato mundial na Copa do Mundo FIFA de 1970!' },
    { id: 3, nome: 'Didi', src: '/assets/Didi.jpeg', descricao: ' Waldir Pereira, mais conhecido como Didi, foi um futebolista brasileiro que atuava como meia. Defendeu a Seleção Brasileira em três Copas do Mundo, sendo campeão das duas últimas. Eleito o melhor jogador da Copa de 1958 pela FIFA e selecionado para a seleção do Mundial de 1962.' },
    { id: 4, nome: 'Garrincha', src: '/assets/Garrincha.jpeg', descricao: 'Manoel Francisco dos Santos, mais conhecido como Garrincha, foi um futebolista brasileiro que atuou como ponta-direita. Notabilizado pela grande habilidade e por seus dribles desconcertantes, Garrincha é considerado por muitos como o mais célebre ponta-direita e o melhor driblador da história do futebol.' },
    { id: 5, nome: 'Gerson', src: '/assets/Gerson.jpeg', descricao: 'Gérson de Oliveira Nunes é um ex-futebolista brasileiro que atuava como meio-campista. Jogou em diversos clubes brasileiros de futebol, tendo passagem destacada no Botafogo.' },
    { id: 6, nome: 'Heleno de Freitas', src: '/assets/Heleno de Freitas.jpeg', descricao: 'Heleno de Freitas foi um futebolista brasileiro. Atuava como centroavante, considerado o primeiro "craque problema" do futebol brasileiro.' },
    { id: 7, nome: 'Jairzinho', src: '/assets/Jairzinho.jpeg', descricao: 'EJair Ventura Filho, mais conhecido como Jairzinho, é um ex-treinador e ex-futebolista brasileiro que atuava como ponta-direita. Jairzinho disputou três Copas do Mundo, em 1966, 1970 e 1974, conquistando o mundo em 1970.' },
    { id: 8, nome: 'Manga', src: '/assets/Manga.jpeg', descricao: 'Haílton Corrêa de Arruda, mais conhecido como Manga é um ex-futebolista brasileiro. Manga foi, segundo a crítica especializada, um dos melhores goleiros da história do futebol brasileiro. É o jogador brasileiro que tem o recorde de participação em edições na Copa Libertadores.' },
    { id: 9, nome: 'Marinho de Chagas', src: '/assets/Marinho de Chagas.jpeg', descricao: 'Francisco das Chagas Marinho, mais conhecido como Marinho Chagas foi um futebolista brasileiro que atuou como lateral-esquerdo, apesar de ser destro.' },
    { id: 10, nome: 'Nilton Santos', src: '/assets/Nilton Santos.jpeg', descricao: 'Nilton dos Santos, mais conhecido como Nilton Santos, foi um futebolista brasileiro que atuava como lateral-esquerdo. Em 2000, foi eleito pela FIFA como o melhor lateral-esquerdo de todos os tempos. Ganhou o mundo em 58 e 62.' },
    { id: 11, nome: 'Paulo Cesar Caju', src: '/assets/Paulo Cesar Caju.jpeg', descricao: 'Paulo Cézar Lima, mais conhecido como Paulo Cézar Caju é um ex-futebolista brasileiro, que atuava como meia e ponta-esquerda.' },
    { id: 12, nome: 'Quarentinha', src: '/assets/Quarentinha.jpeg', descricao: 'Waldir Cardoso Lebrêgo, o Quarentinha, foi um futebolista brasileiro que atuou como centroavante. Até hoje, é o maior artilheiro da história do Botafogo, com 313 gols em 442 jogos. Tem a segunda melhor média de gols da história da Seleção Brasileira: 1 gol por jogo.' },
    { id: 13, nome: 'Sebastião Leonidas', src: '/assets/Sebastião Leonidas.jpeg', descricao: 'Sebastião Leônidas, ou simplesmente Leônidas é um ex-futebolista e treinador brasileiro. Ganhou o brasileirão de 68 pelo fogão' },
    { id: 14, nome: 'Zagallo', src: '/assets/Zagallo.jpeg', descricao: 'Mário Jorge Lobo Zagallo é um ex-treinador e ex-futebolista brasileiro que atuava como ponta-esquerda. Ele detém o recorde de títulos das Copas do Mundo FIFA em geral.' }
]

export default selecionadoDados